// <auto-generated> - Template:AdminEditViewModel, Version:2021.11.12, Id:17ae856a-a589-40c0-a5be-1579b0714385
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.JSInterop;
using ArtistSiteAAD.Client.Services;
using ArtistSiteAAD.Client.Shared;
using ArtistSiteAAD.Shared.Constants;
using ArtistSiteAAD.Shared.DTO;
using MudBlazor;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace ArtistSiteAAD.Client.Pages.Admin
{
	[Authorize]
	public partial class ASArtworkEditViewModel : AdminPageBase
	{
		public Artwork Artwork { get; set; } = new Artwork();

		[Inject]
		public IWebApiDataServiceAS WebApiDataServiceAS { get; set; }

		[Parameter]
		public int ArtworkId { get; set; }

		protected override async Task OnInitializedAsync()
		{
				await base.OnInitializedAsync();

				List<BreadcrumbItem> breadcrumbs = new List<BreadcrumbItem>()
				{
						new BreadcrumbItem("Home", "/"),
						new BreadcrumbItem("List of Artworks", "/admin/artworks"),
						new BreadcrumbItem("Edit Artwork", $"/admin/artworkedit/{ArtworkId}", disabled: true)
				};

				NavigationService.SetBreadcrumbs(breadcrumbs);
		}

		protected async override Task OnParametersSetAsync()
		{
				IsReady = false;
				await SetSavedAsync(false);

				try
				{
						if (ArtworkId == 0) // A new item is being created - opportunity to populate initial/default state
						{
								// Define entity defaults
								Artwork = new Artwork { };
						}
						else
						{
								if (Artwork == null || Artwork.ArtworkId != ArtworkId)
								{
										var result = await WebApiDataServiceAS.GetArtworkAsync(ArtworkId);
										if (result.IsSuccessStatusCode)
										{
												var artwork = result.Data;
												Artwork = artwork;
										}
								}
						}
				}
				finally
				{
						IsReady = true;
				}
		}

		protected async Task OnValidSubmit()
		{
				await SetSavedAsync(false);

				ClearNoneValues();

				if (ArtworkId == 0) // A new item is being created - opportunity to populate initial/default state
				{
						var result = await WebApiDataServiceAS.CreateArtworkAsync(Artwork);
						if (result.IsSuccessStatusCode)
						{
								Artwork = result.Data;
								StatusClass = "alert-success";
								Message = "New item added successfully.";
								await SetSavedAsync(true);
						}
						else
						{
								StatusClass = "alert-danger";
								Message = "Something went wrong adding the new item. Please try again.";
								await SetSavedAsync(false);
						}
				}
				else
				{
						var result = await WebApiDataServiceAS.UpdateArtworkAsync(Artwork);
						if (result.IsSuccessStatusCode)
						{
								StatusClass = "alert-success";
								Message = "Artwork updated successfully.";
								await SetSavedAsync(true);
						}
						else
						{
								StatusClass = "alert-danger";
								Message = "Something went wrong updating the new item. Please try again.";
								await SetSavedAsync(false);
						}
				}
		}

		protected void ReturnToList()
		{
				NavigationManager.NavigateTo("/admin/artworks");
		}

        protected async Task SetSavedAsync(bool value)
        {
            Saved = value;
            if (value == true)
            {
                await JsRuntime.InvokeVoidAsync("blazorExtensions.ScrollToTop");
            }
        }

        private void ClearNoneValues()
        {
            // Add handling for null values here
        }
	}
}

