// <auto-generated> - Template:GenericFactoryInterface, Version:2021.9.14, Id:2bed5905-ced6-4ce8-93ee-eb63365b87ec
using System.Collections.Generic;

namespace ArtistSite.Repository.Mappers
{
public interface IASGenericFactory<TEntity, TDto>
{
	TEntity Create(TDto item);

	TDto Create(TEntity item);

	object CreateDataShapedObject(object item, List<string> fieldList);

	object CreateDataShapedObject(TEntity item, List<string> lstOfFields);

	}
}
