// <auto-generated> - Template:DTO, Version:2021.11.12, Id:c97fab8d-db03-4f94-9c85-14d1f9b41aa7
using System;
using System.Collections.Generic;

namespace ArtistSite.Shared.DTO
{
	public partial class Artist
{
		public Artist()
		{
				InitializePartial();
		}

		// Primary Key
		public int ArtistId { get; set; }

		public string AboutBlurb { get; set; }

		public string AppBarImgSrcLarge { get; set; }

		public string AppBarImgSrcSmall { get; set; }

		public string Code { get; set; }

		public int DisplayOrder { get; set; }

		public string Email { get; set; }

		public string FooterCssClass { get; set; }

		public string HeaderCssClass { get; set; }

		public bool IsActive { get; set; }

		public string MainContentCssClass { get; set; }

		public string Name { get; set; }

		public virtual ICollection<Artwork> Artworks { get; set; } = new List<Artwork>(); // Many to many mapping

		public virtual ICollection<Category> Categories { get; set; } = new List<Category>(); // Many to many mapping

		partial void InitializePartial();
	}
}
