// <auto-generated> - Template:DTO, Version:2021.11.12, Id:c97fab8d-db03-4f94-9c85-14d1f9b41aa7
using System;
using System.Collections.Generic;

namespace ArtistSite.Shared.DTO
{
	public partial class NewsItem
{
		public NewsItem()
		{
				InitializePartial();
		}

		// Primary Key
		public int NewsItemId { get; set; }

		public string Headline { get; set; }

		public string NewsCopy { get; set; }

		partial void InitializePartial();
	}
}
