// <auto-generated> - Template:APIControllerCustom, Version:2022.06.09, Id:44d5b085-471a-4f79-9440-4254c967f282
using ArtistSite.Repository.Infrastructure;
using ArtistSite.Repository.Repositories;
using entAS = ArtistSite.Repository.Entities;
using Enums = ArtistSite.Shared.Constants.Enums;

namespace ArtistSite.Api.Controllers
{
	public partial class MediumController
	{
		protected IASRepository MediumRepository { get; set; }
		protected override void RunCustomLogicAfterCtor()
		{
			MediumRepository = ServiceProvider.GetService<IASRepository>();
		}

		partial void RunCustomLogicAfterInsert(ref entAS.Medium newDBItem, ref IRepositoryActionResult<entAS.Medium> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePatch(ref entAS.Medium updatedDBItem, ref IRepositoryActionResult<entAS.Medium> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePut(ref entAS.Medium updatedDBItem, ref IRepositoryActionResult<entAS.Medium> result)
		{

		}

		partial void RunCustomLogicBeforeUpdatePut(ref entAS.Medium updatedDBItem, int mediumId)
		{

		}

		partial void RunCustomLogicOnGetEntityByPK(ref entAS.Medium dbItem, int mediumId, Enums.RelatedEntitiesType relatedEntitiesType)
		{

		}

	}
}
