// <auto-generated> - Template:APIControllerCustom, Version:2022.06.09, Id:44d5b085-471a-4f79-9440-4254c967f282
using ArtistSiteAAD.Repository.Infrastructure;
using ArtistSiteAAD.Repository.Repositories;
using entAS = ArtistSiteAAD.Repository.Entities;
using Enums = ArtistSiteAAD.Shared.Constants.Enums;

namespace ArtistSiteAAD.Api.Controllers
{
	public partial class ArtistController
	{
		protected IASRepository ArtistRepository { get; set; }
		protected override void RunCustomLogicAfterCtor()
		{
			ArtistRepository = ServiceProvider.GetService<IASRepository>();
		}

		partial void RunCustomLogicAfterInsert(ref entAS.Artist newDBItem, ref IRepositoryActionResult<entAS.Artist> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePatch(ref entAS.Artist updatedDBItem, ref IRepositoryActionResult<entAS.Artist> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePut(ref entAS.Artist updatedDBItem, ref IRepositoryActionResult<entAS.Artist> result)
		{

		}

		partial void RunCustomLogicBeforeUpdatePut(ref entAS.Artist updatedDBItem, int artistId)
		{

		}

		partial void RunCustomLogicOnGetEntityByPK(ref entAS.Artist dbItem, int artistId, Enums.RelatedEntitiesType relatedEntitiesType)
		{

		}

	}
}
