// <auto-generated> - Template:APIControllerCustom, Version:2022.06.09, Id:44d5b085-471a-4f79-9440-4254c967f282
using ArtistSiteAAD.Repository.Infrastructure;
using ArtistSiteAAD.Repository.Repositories;
using entAS = ArtistSiteAAD.Repository.Entities;
using Enums = ArtistSiteAAD.Shared.Constants.Enums;

namespace ArtistSiteAAD.Api.Controllers
{
	public partial class ArtworkMediumXrefController
	{
		protected IASRepository ArtworkMediumXrefRepository { get; set; }
		protected override void RunCustomLogicAfterCtor()
		{
			ArtworkMediumXrefRepository = ServiceProvider.GetService<IASRepository>();
		}

		partial void RunCustomLogicAfterInsert(ref entAS.ArtworkMediumXref newDBItem, ref IRepositoryActionResult<entAS.ArtworkMediumXref> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePatch(ref entAS.ArtworkMediumXref updatedDBItem, ref IRepositoryActionResult<entAS.ArtworkMediumXref> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePut(ref entAS.ArtworkMediumXref updatedDBItem, ref IRepositoryActionResult<entAS.ArtworkMediumXref> result)
		{

		}

		partial void RunCustomLogicBeforeUpdatePut(ref entAS.ArtworkMediumXref updatedDBItem, int artworkId, int mediumId)
		{

		}

		partial void RunCustomLogicOnGetEntityByPK(ref entAS.ArtworkMediumXref dbItem, int artworkId, int mediumId, Enums.RelatedEntitiesType relatedEntitiesType)
		{

		}

	}
}
