// <auto-generated> - Template:APIControllerCustom, Version:2022.06.09, Id:44d5b085-471a-4f79-9440-4254c967f282
using ArtistSiteAAD.Repository.Infrastructure;
using ArtistSiteAAD.Repository.Repositories;
using entAS = ArtistSiteAAD.Repository.Entities;
using Enums = ArtistSiteAAD.Shared.Constants.Enums;

namespace ArtistSiteAAD.Api.Controllers
{
	public partial class ArtworkController
	{
		protected IASRepository ArtworkRepository { get; set; }
		protected override void RunCustomLogicAfterCtor()
		{
			ArtworkRepository = ServiceProvider.GetService<IASRepository>();
		}

		partial void RunCustomLogicAfterInsert(ref entAS.Artwork newDBItem, ref IRepositoryActionResult<entAS.Artwork> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePatch(ref entAS.Artwork updatedDBItem, ref IRepositoryActionResult<entAS.Artwork> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePut(ref entAS.Artwork updatedDBItem, ref IRepositoryActionResult<entAS.Artwork> result)
		{

		}

		partial void RunCustomLogicBeforeUpdatePut(ref entAS.Artwork updatedDBItem, int artworkId)
		{

		}

		partial void RunCustomLogicOnGetEntityByPK(ref entAS.Artwork dbItem, int artworkId, Enums.RelatedEntitiesType relatedEntitiesType)
		{

		}

	}
}
