// <auto-generated> - Template:APIControllerCustom, Version:2022.06.09, Id:44d5b085-471a-4f79-9440-4254c967f282
using ArtistSiteAAD.Repository.Infrastructure;
using ArtistSiteAAD.Repository.Repositories;
using entAS = ArtistSiteAAD.Repository.Entities;
using Enums = ArtistSiteAAD.Shared.Constants.Enums;

namespace ArtistSiteAAD.Api.Controllers
{
	public partial class CategoryController
	{
		protected IASRepository CategoryRepository { get; set; }
		protected override void RunCustomLogicAfterCtor()
		{
			CategoryRepository = ServiceProvider.GetService<IASRepository>();
		}

		partial void RunCustomLogicAfterInsert(ref entAS.Category newDBItem, ref IRepositoryActionResult<entAS.Category> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePatch(ref entAS.Category updatedDBItem, ref IRepositoryActionResult<entAS.Category> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePut(ref entAS.Category updatedDBItem, ref IRepositoryActionResult<entAS.Category> result)
		{

		}

		partial void RunCustomLogicBeforeUpdatePut(ref entAS.Category updatedDBItem, int categoryId)
		{

		}

		partial void RunCustomLogicOnGetEntityByPK(ref entAS.Category dbItem, int categoryId, Enums.RelatedEntitiesType relatedEntitiesType)
		{

		}

	}
}
