// <auto-generated> - Template:APIControllerCustom, Version:2022.06.09, Id:44d5b085-471a-4f79-9440-4254c967f282
using ArtistSiteAAD.Repository.Infrastructure;
using ArtistSiteAAD.Repository.Repositories;
using entAS = ArtistSiteAAD.Repository.Entities;
using Enums = ArtistSiteAAD.Shared.Constants.Enums;

namespace ArtistSiteAAD.Api.Controllers
{
	public partial class NewsItemController
	{
		protected IASRepository NewsItemRepository { get; set; }
		protected override void RunCustomLogicAfterCtor()
		{
			NewsItemRepository = ServiceProvider.GetService<IASRepository>();
		}

		partial void RunCustomLogicAfterInsert(ref entAS.NewsItem newDBItem, ref IRepositoryActionResult<entAS.NewsItem> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePatch(ref entAS.NewsItem updatedDBItem, ref IRepositoryActionResult<entAS.NewsItem> result)
		{

		}

		partial void RunCustomLogicAfterUpdatePut(ref entAS.NewsItem updatedDBItem, ref IRepositoryActionResult<entAS.NewsItem> result)
		{

		}

		partial void RunCustomLogicBeforeUpdatePut(ref entAS.NewsItem updatedDBItem, int newsItemId)
		{

		}

		partial void RunCustomLogicOnGetEntityByPK(ref entAS.NewsItem dbItem, int newsItemId, Enums.RelatedEntitiesType relatedEntitiesType)
		{

		}

	}
}
